### CA1 – Data Preparation and Exploratory Data Analysis

**Module:** Data Preparation     
**Programme:** Higher Diploma in Data Analytics for Business  
**Student ID:** 2026328  
**Assignment:** CA1  
**Project Topic:** Student Academic Outcome Analysis Using Data Preparation and PCA    
**GitHub Repository:** https://github.com/2026328-Dashzeveg-Purevtogtokh/Data-Preparation-Sep26

### Introduction
This project focuses on preparing and analysing student data. The dataset contains information about students, including their background and academic results. The main aim is to check data quality, clean the data, and explore important patterns. PCA will also be used to reduce the number of features while keeping 99.5% of the variance.

In [1]:
# Import my packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load my dataset
df = pd.read_csv("../data/student_dataV2.csv")
print("Dataset loaded:", df.shape)
display(df.head())

Dataset loaded: (4424, 37)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [2]:
# Standardise text values
df.columns = df.columns.str.strip().str.lower()
print(df.columns.tolist())

['marital status', 'application mode', 'application order', 'course', 'daytime/evening attendance', 'previous qualification', 'previous qualification (grade)', 'nacionality', "mother's qualification", "father's qualification", "mother's occupation", "father's occupation", 'admission grade', 'displaced', 'educational special needs', 'debtor', 'tuition fees up to date', 'gender', 'scholarship holder', 'age at enrollment', 'international', 'curricular units 1st sem (credited)', 'curricular units 1st sem (enrolled)', 'curricular units 1st sem (evaluations)', 'curricular units 1st sem (approved)', 'curricular units 1st sem (grade)', 'curricular units 1st sem (without evaluations)', 'curricular units 2nd sem (credited)', 'curricular units 2nd sem (enrolled)', 'curricular units 2nd sem (evaluations)', 'curricular units 2nd sem (approved)', 'curricular units 2nd sem (grade)', 'curricular units 2nd sem (without evaluations)', 'unemployment rate', 'inflation rate', 'gdp', 'target']

In [ ]:
# Standardise column names
df.columns = [
    col.strip().lower().replace(" ", "_").replace("'", "_") for col in df.columns
]

In [4]:
df = df.map(lambda s: s.lower() if isinstance(s, str) else s)

In [5]:
df.head()

,marital_status,application_mode,application_order,course,daytime/evening_attendance,previous_qualification,previous_qualification_(grade),nacionality,mother_s_qualification,father_s_qualification,...,curricular_units_2nd_sem_(credited),curricular_units_2nd_sem_(enrolled),curricular_units_2nd_sem_(evaluations),curricular_units_2nd_sem_(approved),curricular_units_2nd_sem_(grade),curricular_units_2nd_sem_(without_evaluations),unemployment_rate,inflation_rate,gdp,target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,graduate

### 1. Dataset characterisation

In [6]:
# Dataset size
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 4424
Columns: 37

In [7]:
# Data quality checks
print("Missing (NaN):", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Missing (NaN): 21
Duplicate rows: 0

In [8]:
# Data types
print("\nData types:")
print(df.dtypes)

Data types:
marital_status                                        str
application_mode                                  float64
application_order                                 float64
course                                            float64
daytime/evening_attendance                          int64
previous_qualification                              int64
previous_qualification_(grade)                    float64
nacionality                                           str
mother_s_qualification                              int64
father_s_qualification                            float64
mother_s_occupation                               float64
father_s_occupation                                   str
admission_grade                                   float64
displaced                                             str
educational_special_needs                           int64
debtor                                            float64
tuition_fees_up_to_date                               str
gender                                              int64
scholarship_holder                                  int64
age_at_enrollment                                     str
international                                     float64
curricular_units_1st_sem_(credited)                   str
curricular_units_1st_sem_(enrolled)                 int64
curricular_units_1st_sem_(evaluations)              int64
curricular_units_1st_sem_(approved)                 int64
curricular_units_1st_sem_(grade)                  float64
curricular_units_1st_sem_(without_evaluations)      int64
curricular_units_2nd_sem_(credited)                 int64
curricular_units_2nd_sem_(enrolled)               float64
curricular_units_2nd_sem_(evaluations)              int64
curricular_units_2nd_sem_(approved)                 int64
curricular_units_2nd_sem_(grade)                  float64
curricular_units_2nd_sem_(without_evaluations)      int64
unemployment_rate                                 float64
inflation_rate                                    float64
gdp                                               float64
target                                                str
dtype: object

In [9]:
# Target categories
print("\nTarget distribution:")
print(df["target"].value_counts(dropna=False))

Target distribution:
target
graduate    2208
dropout     1420
enrolled     794
grad           1
drop           1
Name: count, dtype: int64

In [10]:
# Target percentages
print("\nTarget percentages:")
print(df["target"].value_counts(normalize=True) * 100)

Target percentages:
target
graduate    49.909584
dropout     32.097649
enrolled    17.947559
grad         0.022604
drop         0.022604
Name: proportion, dtype: float64

**Interpretation:** The dataset contains **4,424 student records and 37 columns**. There are 36 input features and one target variable. The dataset has 21 missing values (NaN) and no duplicate rows.
One important issue is the missing values. Missing data can affect the quality of the analysis and may cause problems when applying PCA. Therefore, missing values need to be checked and handled before further analysis.

### 2. Read the data dictionary and choose data types
Some columns contain measurements, for example age and admission grade. Other columns use numbers as category labels, for example gender and course. We should not treat category labels as measurements.

In [11]:
# Import my dataset
dictionary = pd.read_excel("../data/student_data_dictionary.xlsx")
dictionary.head()

,Variable Name,Role,Type,Demographic,Description,Units
0,Marital Status,Feature,Integer,Marital Status,1 – single 2 – married 3 – widower 4 – divorce...,NaN
1,Application mode,Feature,Integer,NaN,1 - 1st phase - general contingent 2 - Ordinan...,NaN
2,Application order,Feature,Integer,NaN,Application order (between 0 - first choice; a...,NaN
3,Course,Feature,Integer,NaN,33 - Biofuel Production Technologies 171 - Ani...,NaN
4,Daytime/evening attendance,Feature,Integer,NaN,1 – daytime 0 - evening,NaN

In [12]:
dictionary.columns = dictionary.columns.str.strip().str.lower()
print(dictionary.columns.tolist())

['variable name', 'role', 'type', 'demographic', 'description', 'units']

In [ ]:
# Rename target value
dictionary.columns = [
    col.strip().lower().replace(" ", "_") for col in dictionary.columns
]

In [14]:
dictionary = dictionary.map(lambda s: s.lower() if isinstance(s, str) else s)

In [15]:
# Check the dictionary
print("Dictionary shape:", dictionary.shape)
print("Dictionary columns:", dictionary.columns.tolist())

Dictionary shape: (37, 6)
Dictionary columns: ['variable_name', 'role', 'type', 'demographic', 'description', 'units']

In [ ]:
category_cols = df.select_dtypes(
    include=["object", "string", "category", "bool"]
).columns.tolist()

numeric_cols = df.select_dtypes(include="number").columns.tolist()

print("Categorical columns:", category_cols)
print("Numerical columns:", numeric_cols)

Categorical columns: ['marital_status', 'nacionality', 'father_s_occupation', 'displaced', 'tuition_fees_up_to_date', 'age_at_enrollment', 'curricular_units_1st_sem_(credited)', 'target']
Numerical columns: ['application_mode', 'application_order', 'course', 'daytime/evening_attendance', 'previous_qualification', 'previous_qualification_(grade)', 'mother_s_qualification', 'father_s_qualification', 'mother_s_occupation', 'admission_grade', 'educational_special_needs', 'debtor', 'gender', 'scholarship_holder', 'international', 'curricular_units_1st_sem_(enrolled)', 'curricular_units_1st_sem_(evaluations)', 'curricular_units_1st_sem_(approved)', 'curricular_units_1st_sem_(grade)', 'curricular_units_1st_sem_(without_evaluations)', 'curricular_units_2nd_sem_(credited)', 'curricular_units_2nd_sem_(enrolled)', 'curricular_units_2nd_sem_(evaluations)', 'curricular_units_2nd_sem_(approved)', 'curricular_units_2nd_sem_(grade)', 'curricular_units_2nd_sem_(without_evaluations)', 'unemployment_rate', 'inflation_rate', 'gdp']

In [19]:
dictionary

,variable_name,role,type,demographic,description,units
0,marital status,feature,integer,marital status,1 – single 2 – married 3 – widower 4 – divorce...,NaN
1,application mode,feature,integer,NaN,1 - 1st phase - general contingent 2 - ordinan...,NaN
2,application order,feature,integer,NaN,application order (between 0 - first choice; a...,NaN
3,course,feature,integer,NaN,33 - biofuel production technologies 171 - ani...,NaN
4,daytime/evening attendance,feature,integer,NaN,1 – daytime 0 - evening,NaN
5,previous qualification,feature,integer,education level,1 - secondary education 2 - higher education -...,NaN
6,previous qualification (grade),feature,continuous,NaN,grade of previous qualification (between 0 and...,NaN
7,nacionality,feature,integer,nationality,1 - portuguese; 2 - german; 6 - spanish; 11 - ...,NaN
8,mother's qualification,feature,integer,education level,1 - secondary education - 12th year of schooli...,NaN
9,father's qualification,feature,integer,education level,1 - secondary education - 12th year of schooli...,NaN
10,mother's occupation,feature,integer,occupation,0 - student 1 - representatives of the legisla...,NaN
11,father's occupation,feature,integer,occupation,0 - student 1 - representatives of the legisla...,NaN
12,admission grade,feature,continuous,NaN,admission grade (between 0 and 200),NaN
13,displaced,feature,integer,NaN,1 – yes 0 – no,NaN
14,educational special needs,feature,integer,NaN,1 – yes 0 – no,NaN
15,debtor,feature,integer,NaN,1 – yes 0 – no,NaN
16,tuition fees up to date,feature,integer,NaN,1 – yes 0 – no,NaN
17,gender,feature,integer,gender,1 – male 0 – female,NaN
18,scholarship holder,feature,integer,NaN,1 – yes 0 – no,NaN
19,age at enrollment,feature,integer,age,age of studend at enrollment,NaN
20,international,feature,integer,NaN,1 – yes 0 – no,NaN
21,curricular units 1st sem (credited),feature,integer,NaN,number of curricular units credited in the 1st...,NaN
22,curricular units 1st sem (enrolled),feature,integer,NaN,number of curricular units enrolled in the 1st...,NaN
23,curricular units 1st sem (evaluations),feature,integer,NaN,number of evaluations to curricular units in t...,NaN
24,curricular units 1st sem (approved),feature,integer,NaN,number of curricular units approved in the 1st...,NaN
25,curricular units 1st sem (grade),feature,integer,NaN,grade average in the 1st semester (between 0 a...,NaN
26,curricular units 1st sem (without evaluations),feature,integer,NaN,number of curricular units without evalutions ...,NaN
27,curricular units 2nd sem (credited),feature,integer,NaN,number of curricular units credited in the 2nd...,NaN
28,curricular units 2nd sem (enrolled),feature,integer,NaN,number of curricular units enrolled in the 2nd...,NaN
29,curricular units 2nd sem (evaluations),feature,integer,NaN,number of evaluations to curricular units in t...,NaN
30,curricular units 2nd sem (approved),feature,integer,NaN,number of curricular units approved in the 2nd...,NaN
31,curricular units 2nd sem (grade),feature,integer,NaN,grade average in the 2nd semester (between 0 a...,NaN
32,curricular units 2nd sem (without evaluations),feature,integer,NaN,number of curricular units without evalutions ...,NaN
33,unemployment rate,feature,continuous,NaN,unemployment rate (%),NaN
34,inflation rate,feature,continuous,NaN,inflation rate (%),NaN
35,gdp,feature,continuous,NaN,gdp,NaN
36,target,target,categorical,NaN,target. the problem is formulated as a three c...,NaN

In [20]:
df

,marital_status,application_mode,application_order,course,daytime_evening_attendance,previous_qualification,previous_qualification_grade,nationality,mother_s_qualification,father_s_qualification,...,curricular_units_2nd_sem_credited,curricular_units_2nd_sem_enrolled,curricular_units_2nd_sem_evaluations,curricular_units_2nd_sem_approved,curricular_units_2nd_sem_grade,curricular_units_2nd_sem_without_evaluations,unemployment_rate,inflation_rate,gdp,target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1.0,6.0,9773.0,1,1,125.0,1,1,1.0,...,0,6.0,8,5,12.666667,0,15.5,2.8,-4.06,graduate
4420,1,1.0,2.0,9773.0,1,1,120.0,105,1,1.0,...,0,6.0,6,2,11.000000,0,11.1,0.6,2.02,dropout
4421,1,1.0,1.0,9500.0,1,1,154.0,1,37,37.0,...,0,8.0,9,1,13.500000,0,13.9,-0.3,0.79,dropout
4422,1,1.0,1.0,9147.0,1,1,180.0,1,37,37.0,...,0,5.0,6,5,12.000000,0,9.4,-0.8,-3.12,graduate
4423,1,10.0,1.0,9773.0,1,1,152.0,22,38,37.0,...,0,6.0,6,6,13.000000,0,12.7,3.7,-1.70,graduate

In [ ]:
# Clean column names my data frame
df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("'", "_", regex=False)
)

# Fix spelling
df = df.rename(columns={"nacionality": "nationality"})
print(df.columns.tolist())

In [ ]:
# Clean variable names for dictionary file
dictionary["variable_name"] = (
    dictionary["variable_name"]
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("'", "_", regex=False)
)

# Fix spelling in the values
dictionary["variable_name"] = dictionary["variable_name"].replace(
    {"nacionality": "nationality"}
)

print(dictionary["variable_name"].tolist())

['marital_status', 'application_mode', 'application_order', 'course', 'daytime_evening_attendance', 'previous_qualification', 'previous_qualification_grade', 'nationality', 'mother_s_qualification', 'father_s_qualification', 'mother_s_occupation', 'father_s_occupation', 'admission_grade', 'displaced', 'educational_special_needs', 'debtor', 'tuition_fees_up_to_date', 'gender', 'scholarship_holder', 'age_at_enrollment', 'international', 'curricular_units_1st_sem_credited', 'curricular_units_1st_sem_enrolled', 'curricular_units_1st_sem_evaluations', 'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade', 'curricular_units_1st_sem_without_evaluations', 'curricular_units_2nd_sem_credited', 'curricular_units_2nd_sem_enrolled', 'curricular_units_2nd_sem_evaluations', 'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade', 'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate', 'inflation_rate', 'gdp', 'target']

In [23]:
# Numeric features
numeric_cols = [
    "application_order",
    "previous_qualification_grade",
    "admission_grade",
    "age_at_enrollment",
    "curricular_units_1st_sem_credited",
    "curricular_units_1st_sem_enrolled",
    "curricular_units_1st_sem_evaluations",
    "curricular_units_1st_sem_approved",
    "curricular_units_1st_sem_grade",
    "curricular_units_1st_sem_without_evaluations",
    "curricular_units_2nd_sem_credited",
    "curricular_units_2nd_sem_enrolled",
    "curricular_units_2nd_sem_evaluations",
    "curricular_units_2nd_sem_approved",
    "curricular_units_2nd_sem_grade",
    "curricular_units_2nd_sem_without_evaluations",
    "unemployment_rate",
    "inflation_rate",
    "gdp",
]

# Categorical features
category_cols = [
    "marital_status",
    "application_mode",
    "course",
    "daytime_evening_attendance",
    "previous_qualification",
    "nationality",
    "mother_s_qualification",
    "father_s_qualification",
    "mother_s_occupation",
    "father_s_occupation",
    "displaced",
    "educational_special_needs",
    "debtor",
    "tuition_fees_up_to_date",
    "gender",
    "scholarship_holder",
    "international",
]

In [24]:
# Check that all features are included
input_cols = set(df.columns) - {"target"}
selected_cols = numeric_cols + category_cols

print("Numeric features:", len(numeric_cols))
print("Categorical features:", len(category_cols))
print("Total input features:", len(input_cols))

print("Missing:", input_cols - set(selected_cols))
print("Extra:", set(selected_cols) - input_cols)
print("Overlap:", set(numeric_cols) & set(category_cols))

Numeric features: 19
Categorical features: 17
Total input features: 36
Missing: set()
Extra: set()
Overlap: set()

**Interpretation:** I cleaned the column names by changing them to lowercase and using underscores instead of spaces and special characters. I also checked the data types using the data dictionary. The dataset has 19 numeric features and 17 categorical features.Some categorical features were stored as numbers, such as course, gender, and application mode. I classified them as categorical because these numbers represent different groups.This step helps make the dataset more consistent and prepares the features for further analysis.

In [ ]:
I cleaned the column names by changing them to lowercase and using underscores instead of spaces and special characters. I also checked the data types using the data dictionary.